#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication decomposePar -cellDist
runParallel testBuildStencilsParallel -radius 0.025
runApplication reconstructPar -withZero
